CREATE DATABASE APTECHDB

USE APTECHDB
CREATE TABLE IF NOT EXISTS BATCH(
BATCHID INT PRIMARY KEY AUTO_INCREMENT,
BATCHCODE VARCHAR(5) UNIQUE NOT NULL
)

CREATE TABLE STUDENTS(
STDID INT PRIMARY KEY AUTO_INCREMENT,
STDNAME VARCHAR(255),
STDEMAIL VARCHAR(255) UNIQUE NOT NULL,
BATCHID INT,
FOREIGN KEY (BATCHID) REFERENCES BATCH(BATCHID)
)
INSERT INTO STUDENTS VALUES(NULL,'AHMED KHAN','ahmed@aptechsite.net',2)
INSERT INTO STUDENTS VALUES(NULL,'IMRAN KHAN','IMRAN@aptechsite.net',2),
(NULL,'farhan KHAN','farhan@aptechsite.net',2),(NULL,'irfan KHAN','irfan@aptechsite.net',3),(NULL,'kamran KHAN','kamran@aptechsite.net',3)
DROP TABLE STUDENTS
DROP TABLE BATCH 
INSERT INTO STUDENTS VALUES(NULL,'Wasif KHAN','wasif@aptechsite.net',1)

INSERT INTO BATCH VALUES(NULL,'2201F')
INSERT INTO BATCH VALUES(NULL,'2202F')
INSERT INTO BATCH(BATCHCODE) VALUES('2203F')
SELECT * FROM BATCH
SELECT * FROM STUDENTS

SELECT STDID,STDNAME,STDEMAIL,B.BATCHCODE FROM STUDENTS S
INNER JOIN BATCH B
ON S.BATCHID = B.BATCHID


SELECT COUNT(*),BATCHID FROM 
STUDENTS GROUP BY BATCHID
 
 SELECT B.BATCHCODE,COUNT(*) 'STD #' FROM STUDENTS S
INNER JOIN BATCH B
ON S.BATCHID = B.BATCHID
GROUP BY B.BATCHCODE


